version: '2'
services:
  easy_ssb_pub:
    build: .
    environment:
      PUB_URL: "${PUB_URL}"
      SSB_PATH: /shared/.ssb
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    container_name: easy-ssb-pub
    mem_limit: 450M
    memswap_limit: 1G
    volumes:
      - $HOME/shared:/shared
    restart: unless-stopped
